---
title: "Supp_Fig_3b"
author: "Alecia-Jane Twigger"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

**Setting up**
*Load data and packages*
Firstly we must load the important libraries and then the data.
```{r, message=FALSE}
#load libraries
library(plyr)
library(dplyr)
library(scater)
library(ggplot2)
library(knitr)
library("scatterplot3d")

#specific for dendogram+heatmap
library(cowplot)
library(viridis)
library(RColorBrewer)
library(pheatmap)
library(gridExtra)
library(gridGraphics)
library(dendextend)

#load data
sce <- readRDS("../../data/sce_all_nospike_2.rds")
```

**Supplementary Figure 3b**
Looking at fresh vs. frozen milk cells
```{r}
#mapping fresh vs frozen onto sce
Sample <- c("HMC1","HMC2","HMC3","HMC4","HMC2B","HMC5","HMC6","HMC7","HMC8","HMC9","RB1","RB2","RB3","RB4","RB5","RB6","RB7","RB8")
FreshOrNot <- c("Fresh","Fresh","Fresh","Fresh","Frozen","Frozen","Frozen","Frozen","Frozen","Fresh","Fragment","Fragment","Fragment","Fragment","Fragment","Fragment","Fragment","Fragment")
pD$FreshOrNot <- mapvalues(pD$Sample, Sample, FreshOrNot)

#Colours
fresh <- c("Fresh","Frozen","Fragment")
fresh.colours <- c("orange","orange3", "grey")

#Fresh
Fresh <- dplyr::group_by(pD, FreshOrNot) %>%
          ungroup(FreshOrNot) %>%
          mutate(FreshOrNot=forcats::fct_relevel(FreshOrNot,c("Fragment","Frozen","Fresh"))) %>%
          arrange(FreshOrNot)

UMAP <- ggplot(Fresh, mapping=aes(x=UMAP1, y=UMAP2, color=FreshOrNot)) + 
    geom_point() + scale_color_manual(values=setNames(fresh.colours, fresh)) +
    theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
UMAP
pdf("../../data/Downstream_graphs/UMAP_FreshOrNot.pdf", width=12, height=8)
UMAP
dev.off()

#Frozen
Frozen <- dplyr::group_by(pD, FreshOrNot) %>%
          ungroup(FreshOrNot) %>%
          mutate(FreshOrNot=forcats::fct_relevel(FreshOrNot,c("Fragment","Fresh","Frozen"))) %>%
          arrange(FreshOrNot)

UMAP <- ggplot(Frozen, mapping=aes(x=UMAP1, y=UMAP2, color=FreshOrNot)) + 
    geom_point() + scale_color_manual(values=setNames(fresh.colours, fresh)) +
    theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
UMAP
pdf("../../data/Downstream_graphs/UMAP_FrozenOrNot.pdf", width=12, height=8)
UMAP
dev.off()
```
