---
title: "Supp_Fig_4b"
author: "Alecia"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

**Setting up**
*Load data and packages*
Firstly we must load the important libraries and then the data.
```{r, message=FALSE}
#load libraries
library(plyr)
library(dplyr)
library(scater)
library(ggplot2)
library(knitr)
library("scatterplot3d")

#specific for dendogram+heatmap
library(cowplot)
library(viridis)
library(RColorBrewer)
library(pheatmap)
library(gridExtra)
library(gridGraphics)
library(dendextend)

#load data
sce <- readRDS("../../data/sce_all_nospike_2.rds")
```
**Supplementary Figure 4b**
UMAPs colored by sample
```{r}
#--------------#UMAP colored by sample#--------------#
#All samples colored
sample.set <- c("HMC1", "HMC2", "HMC3","HMC4", "HMC2B","HMC5","HMC6","HMC7","HMC8", "HMC9","RB1", "RB2","RB3","RB4","RB5","RB6","RB7", "RB8")
colour.names <- c("salmon1", "peachpuff2", "burlywood", "#F8766D","peachpuff3", "salmon2", "pink1",  "indianred2", "indianred4", "hotpink2", "steelblue3", "slategray3", "paleturquoise3","#00BFC4","turquoise", "turquoise4", "lightblue1", "lightskyblue2")

UMAP <- ggcells(sce, mapping=aes(x=UMAP1, y=UMAP2, color=Sample)) + 
    geom_point() + scale_color_manual(values=setNames(colour.names, sample.set)) +
    theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
UMAP

pdf("../../data/Downstream_graphs/UMAP_Sample.pdf", width=12, height=8)
UMAP
dev.off()
```