---
title: "Supp_Fig_3_c_d"
author: "Alecia-Jane Twigger"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

**Setting up**

*Load data and packages*
Firstly we must load the important libraries and then the data.
```{r, message=FALSE}
#load libraries
library(plyr)
library(dplyr)
library(scran)
library(scater)
library(ggplot2)
library(knitr)

#load data
sce <- readRDS("../../data/RB_HMC_merged/sce_all_nospike_2.rds")
```
*Check that the data is loaded correctly*
```{r}
sce
```
*Set colors*
```{r}
sample.set <- c("HMC1", "RB1", "HMC3","HMC4", "RB1B","HMC5","HMC6","HMC7","HMC8", "HMC9","RB1", "RB2","RB3","RB4","RB5","RB6","RB7", "RB8")
colour.names <- c("salmon1", "peachpuff2", "burlywood", "#F8766D","peachpuff3", "salmon2", "pink1",  "indianred2", "indianred4", "hotpink2", "steelblue3", "slategray3", "paleturquoise3","#00BFC4","turquoise", "turquoise4", "lightblue1", "lightskyblue2")
```
**Figure 3c**
*PCA of samples from LMC2 from before (LMC2/HMC2) and after freezing (LMC2B/HMC2B)*
```{r}
set.seed(60)

#subsetting to LMC2 samples
sce.HMC2 <- sce[,colData(sce)$Sample=="HMC2"|colData(sce)$Sample=="HMC2B"]

#Finding highly variable genes (hvg)
dec.sce <- modelGeneVar(sce.HMC2)
fit.sce <- metadata(dec.sce)
plot(fit.sce$mean, fit.sce$var, xlab="Mean of log-expression", ylab="Variance of log-expression")
curve(fit.sce$trend(x), col="dodgerblue", add=TRUE, lwd=2)
chosen <- getTopHVGs(dec.sce, prop=0.1)
str(chosen)
sce.hvg.sub <- sce.HMC2[chosen,]
dim(sce.hvg.sub)
altExp(sce.hvg.sub, "original") <-sce.HMC2
altExpNames(sce.hvg.sub)
sce.hvg.sub

#Run PCA and colour 
set.seed(100)
sce.HMC2 <- runPCA(sce.HMC2, dimred="corrected")
reducedDimNames(sce.HMC2)

#Adding PCA data to colData of subsetted sce
PCA <- as.data.frame(reducedDim(sce.HMC2, "PCA"))
colData(sce.HMC2)$PCA1 <- PCA$PC1
colData(sce.HMC2)$PCA2 <- PCA$PC2

#Plotting PCA plot
PCAs.subcluster <- ggcells(sce.HMC2, aes(x=PCA1, y=PCA2, color=Sample))+
    geom_point() +
    xlab("PC1") +
    ylab("PC2") +
    ggtitle("PCAs") +
    theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
    scale_color_manual(values=setNames(colour.names, sample.set))
PCAs.subcluster 
pdf("../../data/Supp_Fig_3/PCA_1_2_HMC2vs2B_Sample.pdf", width=6, height=4)
PCAs.subcluster
dev.off()
```
**Figure 3d**
*PCA of samples from NMC1 from two different batches (NMC1/RB1 and NMC1B/RB8)*
```{r}
set.seed(60)

#subsetting on just RB1 samples
sce.RB1 <- sce[,colData(sce)$Sample=="RB1"|colData(sce)$Sample=="RB8"]

#Finding hvgs
dec.sce <- modelGeneVar(sce.RB1)
fit.sce <- metadata(dec.sce)
plot(fit.sce$mean, fit.sce$var, xlab="Mean of log-expression", ylab="Variance of log-expression")
curve(fit.sce$trend(x), col="dodgerblue", add=TRUE, lwd=2)
chosen <- getTopHVGs(dec.sce, prop=0.1)
str(chosen)
sce.hvg.sub <- sce.RB1[chosen,]
dim(sce.hvg.sub)
altExp(sce.hvg.sub, "original") <-sce.RB1
altExpNames(sce.hvg.sub)
sce.hvg.sub

#Run PCA and colour
set.seed(100)
sce.RB1 <- runPCA(sce.RB1, dimred="corrected")
reducedDimNames(sce.RB1)

#Adding PCA data to colData of subsetted sce
PCA <- as.data.frame(reducedDim(sce.RB1, "PCA"))
colData(sce.RB1)$PCA1 <- PCA$PC1
colData(sce.RB1)$PCA2 <- PCA$PC2

#Plotting PCA plot
PCAs.subcluster <- ggcells(sce.RB1, aes(x=PCA1, y=PCA2, color=Sample))+
    geom_point() +
    xlab("PC1") +
    ylab("PC2") +
    ggtitle("PCAs") +
    theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
    scale_color_manual(values=setNames(colour.names, sample.set))
PCAs.subcluster 
pdf("../../data/Supp_Fig_3/PCA_1_2_RB1vs2B_Sample.pdf", width=6, height=4)
PCAs.subcluster
dev.off()
```
*Saving session info*
```{r}
sessionInfo()
```